name: 'factory_pipeline_dbt'
version: '1.0.0'
config-version: 2
profile: 'localstack'

model-paths: ["models"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  factory_pipeline_dbt:
    raw:
      +materialized: incremental
      +schema: raw
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

vars:
  'sensor_reading_threshold': 100  # Example threshold for sensor readings
  'machine_health_window': 24  # Hours to consider for health metrics
