version: 2

models:
  - name: PROCESSED_MACHINE_HEALTH
    config:
      materialized: ephemeral

    columns:
      - name: machine_id
        description: "The unique identifier for the machine."
        tests:
          - not_null

      - name: health_status
        description: "The calculated health status of the machine."
        tests:
          - not_null
          - accepted_values:
              values: ['HEALTHY', 'NEEDS_MAINTENANCE', 'CRITICAL']

      - name: failure_risk_score
        description: "A score indicating the risk of failure."
        tests:
          - not_null
