[connections.snowflake]
user = "test"
password = "test"
account = "test"
warehouse = "test"
database = "FACTORY_PIPELINE_DEMO"
schema = "PUBLIC"
role = "test"
host = "snowflake.localhost.localstack.cloud"
