version: 2

models:
  - name: processed_machine_health
    description: "Final processed machine health metrics"
    columns:
      - name: machine_id
        description: "Unique identifier for the machine"
        tests:
          - unique
          - not_null
      
      - name: last_reading_time
        description: "Timestamp of the last sensor reading"
        tests:
          - not_null
          
      - name: total_readings
        description: "Total number of readings for the machine"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              
      - name: anomalous_readings
        description: "Count of anomalous readings"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              
      - name: avg_temperature
        description: "Average temperature reading"
        tests:
          - not_null
              
      - name: max_vibration
        description: "Maximum vibration reading"
        tests:
          - not_null
              
      - name: min_signal_strength
        description: "Minimum signal strength"
        tests:
          - not_null

      - name: failure_risk_score
        description: "Calculated risk score for machine failure (0-100)"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 100
              
      - name: health_status
        description: "Current health status of the machine"
        tests:
          - not_null
          - accepted_values:
              values: ['HEALTHY', 'NEEDS_MAINTENANCE', 'CRITICAL']
              
      - name: maintenance_recommendation
        description: "Recommended maintenance action"
        tests:
          - not_null
          - accepted_values:
              values: ['No action needed', 'Schedule maintenance within 48 hours', 'Immediate maintenance required'] 